name: whatsapp_clone
description: "WhatsApp Clone in Flutter 2024"
publish_to: "'none'"
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  any_link_preview: ^3.0.2
  audioplayers: ^6.1.0
  cached_network_image: ^3.4.0
  cached_video_player_plus: ^3.0.3
  camera: ^0.11.0+2
  chat_bubbles: ^1.6.0
  cloud_firestore: ^5.2.1
  country: ^4.1.7
  emoji_picker_flutter: ^2.2.0
  enough_giphy_flutter: ^0.4.1
  file_picker: ^8.0.7
  firebase_analytics: ^11.2.1
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  firebase_storage: ^12.1.3
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_reaction_button: ^3.0.0+3
  flutter_riverpod: ^2.5.1
  flutter_sound: ^9.11.2
  fluttertoast: ^8.2.7
  font_awesome_flutter: ^10.7.0
  go_router: ^14.2.3
  grouped_list: ^6.0.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.3.2
  sliding_up_panel2: ^3.3.0+1
  status_view: ^0.0.2
  story_view: ^0.16.5
  swipe_to: ^1.0.6
  timeago: ^3.7.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/launch-icon.png"
  web:
    generate: true
    image_path: "assets/icons/launch-icon.png"
  windows:
    generate: true
    image_path: "assets/icons/launch-icon.png"

#dart run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: "assets/icons/splash-icon.png"
  android: true
  web: true
  android_12:
    color: "#ffffff"
    image: "assets/icons/splash-icon.png"

analyzer:
  plugins:
    - custom_lint